"""共享配置读写层（无交互、无打印）。

CLI 首启向导（scripts/first_run_setup.py）与 Windows GUI 向导共用这一层，
确保 .env / config.yaml 的写入逻辑只有一份，不会漂移。
"""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path
from typing import Optional

import sys as _sys
if getattr(_sys, "frozen", False):
    # PyInstaller 冻结后 __file__ 指向临时解压目录，
    # 改用 exe 所在目录作为项目根（仅用于展示/定位模板）。
    PROJECT_ROOT = Path(_sys.executable).resolve().parent
else:
    PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _resolve_data_dir() -> Path:
    """决定配置/日志/PID 等可写数据的落点目录。

    决策顺序（先命中先用）：
      1. 环境变量 MIMO_CONNECT_HOME 显式指定；
      2. 向后兼容：可执行/项目同目录已存在 .env，则继续沿用旧位置，
         避免老用户升级后“配置突然消失”；
      3. 默认用户级目录 ~/.config/mimo_connect（遵循 XDG_CONFIG_HOME）。

    这样无论 mmc 被软链到 PATH 何处、用源码还是单文件运行，
    都能稳定读写同一份用户配置，而不会落到 /usr/local/bin 等只读系统目录。
    """
    env_home = os.environ.get("MIMO_CONNECT_HOME", "").strip()
    if env_home:
        return Path(env_home).expanduser()
    # 向后兼容旧布局：可执行/项目同目录已有 .env 就继续用那里。
    legacy = PROJECT_ROOT / ".env"
    if legacy.exists():
        return PROJECT_ROOT
    xdg = os.environ.get("XDG_CONFIG_HOME", "").strip()
    base = Path(xdg).expanduser() if xdg else Path.home() / ".config"
    return base / "mimo_connect"


DATA_DIR = _resolve_data_dir()
ENV_PATH = DATA_DIR / ".env"
CONFIG_PATH = DATA_DIR / "config.yaml"
# 引导过程中途退出时，已填写的字段暂存在这里，下次启动续填。
DRAFT_PATH = DATA_DIR / ".setup_draft.json"
# 运行时产物：日志与守护进程 PID 也落在数据目录。
LOG_PATH = DATA_DIR / "mimo_connect.log"
PID_PATH = DATA_DIR / "mimo_connect.pid"

# 打包(onefile)时 .env.example / config.yaml 模板随程序解压到 sys._MEIPASS；
# 源码运行时就在项目根。用于首次运行自动生成同目录配置文件。
if getattr(_sys, "frozen", False):
    _BUNDLE_DIR = Path(getattr(_sys, "_MEIPASS", PROJECT_ROOT))
else:
    _BUNDLE_DIR = PROJECT_ROOT

# 各提供商默认 base_url / 模型，便于直接采用。
PROVIDER_PRESETS: dict[str, dict[str, str]] = {
    "deepseek": {
        "env_key": "DEEPSEEK_API_KEY",
        "base_url": "https://api.deepseek.com",
        "model": "deepseek-chat",
    },
    "openai": {
        "env_key": "OPENAI_API_KEY",
        "base_url": "https://api.openai.com/v1",
        "model": "gpt-4o",
    },
    "anthropic": {
        "env_key": "ANTHROPIC_API_KEY",
        "base_url": "https://api.anthropic.com",
        "model": "claude-sonnet-4-20250514",
    },
    "siliconflow": {
        "env_key": "SILICONFLOW_API_KEY",
        "base_url": "https://api.siliconflow.cn/v1",
        "model": "deepseek-ai/DeepSeek-V4-Flash",
    },
    "dashscope": {
        "env_key": "DASHSCOPE_API_KEY",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model": "deepseek-ai/DeepSeek-V4-Flash",
    },
}

_ENV_HEADER = "# MIMO_Connect config (generated by setup wizard)"
_ENV_HEADER2 = "# To change, edit this file directly or rerun the setup wizard."


def read_env(path: Path | None = None) -> dict[str, str]:
    """解析 .env 为字典；文件不存在时返回空字典。path 为 None 时动态取 ENV_PATH。"""
    if path is None:
        path = ENV_PATH
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip()
    return values


def write_env(values: dict[str, str], path: Path | None = None) -> None:
    """把键值对写入 .env（空值不写）。path 为 None 时动态取 ENV_PATH。"""
    if path is None:
        path = ENV_PATH
    lines = [_ENV_HEADER, _ENV_HEADER2, ""]
    for key, val in values.items():
        if val:
            lines.append(f"{key}={val}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def sync_config_yaml(provider: str, base_url: str, model: str,
                     path: Path | None = None) -> bool:
    """把所选提供商写入 config.yaml 的 active_provider，并更新其 base_url/model。

    返回 True 表示已写入；False 表示缺少 pyyaml 或配置文件不存在。
    """
    if path is None:
        path = CONFIG_PATH
    try:
        import yaml  # type: ignore[import-untyped]
    except Exception:
        return False
    if not path.exists():
        return False
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    llm = data.setdefault("llm", {})
    llm["active_provider"] = provider
    providers = llm.setdefault("providers", {})
    pcfg = providers.setdefault(provider, {})
    pcfg["base_url"] = base_url
    pcfg["model"] = model
    with open(path, "w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
    return True


def find_mimo_cli() -> Optional[str]:
    """跨平台检索 mimo CLI 可执行文件路径。"""
    path = shutil.which("mimo")
    if path:
        return path
    if os.name == "nt":
        search_dirs = [os.path.expanduser("~/AppData/Roaming/npm")]
        names = ["mimo.cmd", "mimo.ps1", "mimo.exe", "mimo"]
    else:
        search_dirs = [
            os.path.expanduser("~/.npm-global/bin"),
            os.path.expanduser("~/.local/bin"),
            "/usr/local/bin",
            "/usr/bin",
            "/opt/homebrew/bin",
        ]
        names = ["mimo"]
    for d in search_dirs:
        for name in names:
            candidate = os.path.join(d, name)
            if os.path.exists(candidate):
                return candidate
    return None


def is_configured(path: Path = ENV_PATH) -> bool:
    """判断是否已完成首次配置：.env 存在、有可用 LLM key、且所选平台凭证齐全。"""
    env = read_env(path)
    if not env:
        return False
    has_llm_key = any(env.get(p["env_key"]) for p in PROVIDER_PRESETS.values())
    if not has_llm_key:
        return False
    platform = env.get("MIMO_CONNECT_PLATFORM", "").lower()
    if platform in ("feishu", "lark"):
        return bool(env.get("FEISHU_APP_ID") and env.get("FEISHU_APP_SECRET"))
    if platform == "weixin":
        return bool(env.get("WEIXIN_BOT_ID") and env.get("WEIXIN_TOKEN"))
    return True


def read_draft(path: Path | None = None) -> dict[str, str]:
    """读取引导草稿；缺失或损坏时返回空字典。path 为 None 时动态取 DRAFT_PATH。"""
    if path is None:
        path = DRAFT_PATH
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    if not isinstance(data, dict):
        return {}
    # 只保留字符串键值，避免脏数据污染后续写入。
    return {str(k): str(v) for k, v in data.items() if v is not None}


def write_draft(values: dict[str, str], path: Path | None = None) -> None:
    """把当前已填字段写入草稿文件（合并已有草稿，空值不覆盖）。path 为 None 时动态取 DRAFT_PATH。"""
    if path is None:
        path = DRAFT_PATH
    merged = read_draft(path)
    for key, val in values.items():
        if val:
            merged[str(key)] = str(val)
    try:
        path.write_text(
            json.dumps(merged, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
    except Exception:
        # 草稿仅为体验优化，写失败不应阻断引导流程。
        pass


def clear_draft(path: Path | None = None) -> None:
    """配置成功写入后清除草稿。path 为 None 时动态取 DRAFT_PATH。"""
    if path is None:
        path = DRAFT_PATH
    try:
        path.unlink()
    except FileNotFoundError:
        pass
    except Exception:
        pass


# ---- 语言偏好（GUI 与 CLI 共用，存于 .env 的 MIMO_CONNECT_LANG）----

SUPPORTED_LANGS = ("zh", "en")


def detect_system_lang() -> str:
    """探测系统界面语言，返回 "zh" 或 "en"。"""
    if os.name == "nt":
        try:
            import ctypes

            lang_id = ctypes.windll.kernel32.GetUserDefaultUILanguage()
            if (lang_id & 0xFF) == 0x04:  # 主语言 ID 0x04 == 中文
                return "zh"
        except Exception:
            pass
    blob = ""
    try:
        import locale

        blob += (locale.getdefaultlocale()[0] or "") + " "
    except Exception:
        pass
    blob += os.environ.get("LANG", "") + " " + os.environ.get("LC_ALL", "")
    return "zh" if ("zh" in blob.lower() or "chinese" in blob.lower()) else "en"


def read_lang(path: Path | None = None) -> str:
    """读取已保存的语言偏好；缺失或非法时回退到系统语言探测。"""
    env = read_env(path)
    val = (env.get("MIMO_CONNECT_LANG") or "").strip().lower()
    if val in SUPPORTED_LANGS:
        return val
    return detect_system_lang()


def write_lang(lang: str, path: Path | None = None) -> None:
    """把语言偏好写回 .env，保留其余键值不变。"""
    if path is None:
        path = ENV_PATH
    lang = lang.strip().lower()
    if lang not in SUPPORTED_LANGS:
        lang = "zh"
    env = read_env(path)
    env["MIMO_CONNECT_LANG"] = lang
    write_env(env, path)


def ensure_runtime_files() -> None:
    """首次运行时确保可执行同目录存在 .env 与 config.yaml（不覆盖已有）。

    - 打包成单文件后，模板被解压到临时目录；这里把它们落到 exe 同目录，
      使 .env / 日志 / config.yaml 持久化在用户可见、可编辑的位置。
    - 已存在的文件一律保留，绝不覆盖用户配置。
    """
    import shutil

    # 用户级数据目录首次可能不存在，先确保它在，再落地各文件。
    try:
        DATA_DIR.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass

    # .env：缺失则从 .env.example 复制一份占位，让用户/向导有文件可写。
    if not ENV_PATH.exists():
        example = _BUNDLE_DIR / ".env.example"
        try:
            if example.exists():
                shutil.copyfile(example, ENV_PATH)
            else:
                ENV_PATH.write_text(_ENV_HEADER + "\n" + _ENV_HEADER2 + "\n", encoding="utf-8")
        except Exception:
            pass

    # config.yaml：缺失则从打包模板复制（源码运行时通常已存在）。
    if not CONFIG_PATH.exists():
        template = _BUNDLE_DIR / "config.yaml"
        try:
            if template.exists() and template.resolve() != CONFIG_PATH.resolve():
                shutil.copyfile(template, CONFIG_PATH)
        except Exception:
            pass


def read_tts_mimo(path: Path | None = None) -> dict:
    """读取 config.yaml 中 tts.mimo 的当前配置与可选项。

    返回 dict：
      voice   当前音色（缺省 ""）
      model   当前 TTS 模型（缺省 ""）
      api_url 当前接口地址（缺省 ""）
      voices  可选音色列表（从 models[*].voices 汇总去重，供下拉填充）
      models  可选模型名列表
    缺少 pyyaml 或文件不存在时返回带空值的结构。
    """
    result = {"voice": "", "model": "", "api_url": "", "voices": [], "models": []}
    if path is None:
        path = CONFIG_PATH
    try:
        import yaml  # type: ignore[import-untyped]
    except Exception:
        return result
    if not path.exists():
        return result
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception:
        return result
    mimo = ((data.get("tts") or {}).get("mimo") or {})
    result["voice"] = mimo.get("voice", "") or ""
    result["model"] = mimo.get("model", "") or ""
    result["api_url"] = mimo.get("api_url", "") or ""
    models = mimo.get("models") or []
    model_names: list[str] = []
    voices: list[str] = []
    for m in models:
        if not isinstance(m, dict):
            continue
        name = m.get("name")
        if name and name not in model_names:
            model_names.append(name)
        for v in (m.get("voices") or []):
            if v and v not in voices:
                voices.append(v)
    result["models"] = model_names
    result["voices"] = voices
    return result


def write_tts_mimo(voice: str = "", model: str = "", api_url: str = "",
                   path: Path | None = None) -> bool:
    """把 MiMo TTS 的 voice / model / api_url 写回 config.yaml 的 tts.mimo。

    只更新传入的非空字段，保留 models 列表等其它内容不动。
    返回 True 表示已写入；False 表示缺少 pyyaml 或文件不存在。
    """
    if path is None:
        path = CONFIG_PATH
    try:
        import yaml  # type: ignore[import-untyped]
    except Exception:
        return False
    if not path.exists():
        return False
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    tts = data.setdefault("tts", {})
    mimo = tts.setdefault("mimo", {})
    if voice:
        mimo["voice"] = voice
    if model:
        mimo["model"] = model
    if api_url:
        mimo["api_url"] = api_url
    with open(path, "w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
    return True
