"""Progress summarizer: turn the latest MiMo tool-event line into a
short, user-friendly progress description via the **middleware LLM**
(separately configured API key, currently DeepSeek — not MiMo Code's
internal model).

Heartbeat strategy:
- Send the LLM the LATEST status line plus a small context bundle so it
  can interpret the bare event meaningfully.
- Retry up to 3 times on timeout / exception with short backoff.
- After 3 consecutive failures, return a structured error so the engine
  can notify the user with the actual error cause (not a silent fallback).
- On any non-retry-exhausted failure, the engine itself decides whether
  to use the raw last_status as fallback.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)


PROGRESS_SYSTEM_PROMPT = """你是 MIMO_Connect 中间层的进度汇报员。MiMo Code 在后台执行编程任务时会产生工具调用事件，但这些事件对普通用户难以理解。

你的任务：根据「当前正在发生的事件」+「上下文」，用 1-2 句简洁中文向用户报告"它正在干什么"。

要求：
1) 用自然口语，不要复述 category/tool/call_id 等技术字段
2) 必须结合上下文（用户原始任务、之前做过的大类操作）让描述有意义
3) 如果当前事件 status=running，要体现"正在……"
4) 不超过 60 个汉字，不要 markdown
5) 直接输出描述本身，不要"当前进度："之类的前缀"""

PROGRESS_USER_PROMPT = """用户原始任务：
{user_task}

之前已经做过的操作类别（去重）：
{prior_categories}

当前正在发生的事件：
{current_event}

已耗时：约 {elapsed_sec} 秒

请用 1-2 句中文告诉用户它正在做什么。"""


@dataclass
class ProgressResult:
    """Outcome of a summarize call.

    - text: the user-facing description (always present, never empty)
    - ok: True if generated by the LLM, False if it's a fallback / error
    - error: when ok=False and we exhausted retries, this carries the
      last error message so the engine can surface it to the user.
    """
    text: str
    ok: bool = True
    error: str = ""


class ProgressSummarizer:
    """Generates a human-readable progress line via the middleware LLM.

    Args:
        llm_client: middleware LLM (DeepSeek by default), shared with
            intent_router and segment_rewriter — NOT MiMo Code's model.
        timeout: per-attempt timeout in seconds.
        max_retries: total attempts is max_retries (so 3 means: try, retry,
            retry); after exhausting we return ProgressResult(ok=False).
    """

    def __init__(self, llm_client=None, timeout: float = 5.0, max_retries: int = 3):
        self._client = llm_client
        self._timeout = timeout
        self._max_retries = max(1, max_retries)

    def available(self) -> bool:
        return self._client is not None

    async def summarize(
        self,
        latest_status: str,
        user_task: str = "",
        prior_categories: Optional[list[str]] = None,
        elapsed_sec: int = 0,
    ) -> ProgressResult:
        """Summarize the latest status line with context.

        Returns ProgressResult. On exhausted retries, ok=False and error
        contains the last exception message so the engine can tell the
        user what actually broke.
        """
        if not latest_status:
            return ProgressResult(text="正在处理中", ok=True)
        if not self._client:
            # No LLM configured — pass raw status straight through; engine
            # will decide whether to surface it.
            return ProgressResult(
                text=latest_status,
                ok=False,
                error="middleware LLM client is not configured",
            )

        last_error = ""
        for attempt in range(1, self._max_retries + 1):
            try:
                from langchain_core.messages import HumanMessage, SystemMessage

                cats = ", ".join(prior_categories or []) if prior_categories else "（无）"
                messages = [
                    SystemMessage(content=PROGRESS_SYSTEM_PROMPT),
                    HumanMessage(content=PROGRESS_USER_PROMPT.format(
                        user_task=user_task or "（未提供）",
                        prior_categories=cats,
                        current_event=latest_status,
                        elapsed_sec=max(0, elapsed_sec),
                    )),
                ]
                response = await asyncio.wait_for(
                    self._client.ainvoke(messages),
                    timeout=self._timeout,
                )
                text = (response.content or "").strip()
                if not text:
                    last_error = "empty response from LLM"
                    logger.warning(f"ProgressSummarizer attempt {attempt}/{self._max_retries}: {last_error}")
                else:
                    if len(text) > 200:
                        text = text[:200].rstrip() + "…"
                    return ProgressResult(text=text, ok=True)
            except asyncio.TimeoutError:
                last_error = f"timeout after {self._timeout}s"
                logger.warning(f"ProgressSummarizer attempt {attempt}/{self._max_retries}: {last_error}")
            except Exception as e:
                last_error = f"{type(e).__name__}: {e}"
                logger.warning(f"ProgressSummarizer attempt {attempt}/{self._max_retries}: {last_error}")

            # Backoff between attempts (skip after final attempt)
            if attempt < self._max_retries:
                await asyncio.sleep(0.3 * attempt)

        # All retries exhausted — return raw status as text but mark as failed
        # so the engine can surface the error cause to the user.
        return ProgressResult(text=latest_status, ok=False, error=last_error)
